PROBLEM: althogh local make check passes, on jenkins i am getting:
/usr/bin/ld: src/agents/autoconfig/test_autoconfig-RuleConfigurator.o:
undefined reference to symbol 'mlm_client_sendto'
//usr/lib/libmlm.so.0: error adding symbols: DSO missing from command
//line
collect2: error: ld returned 1 exit status
Makefile:3423: recipe for target 'test-autoconfig' failed

SOUTION:
? Let's try to add ${LIBMLM_LIBS}

Signed-off-by: Karol Hrdina <karolhrdina@eaton.com>